# Generated by Django 4.2.13 on 2024-07-08 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=300)),
                ('category', models.CharField(choices=[('Withdrawl', 'Withdrawl'), ('Deposit', 'Deposit')], max_length=20)),
                ('date', models.DateField()),
                ('amount', models.PositiveIntegerField()),
                ('transaction_from_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
        ),
    ]
