# Generated by Django 4.2.13 on 2024-07-11 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_transaction_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('WITHDRAW', 'Withdraw'), ('DEPOSIT', 'Deposit')], max_length=20),
        ),
    ]
