# Generated by Django 4.2.13 on 2024-07-11 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_transaction_is_deleted_alter_transaction_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='is_deleted',
        ),
    ]
