# Generated by Django 4.2.13 on 2024-07-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_alter_transaction_transaction_from_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_reverted',
            field=models.BooleanField(default=False),
        ),
    ]
