# Generated by Django 4.2.13 on 2024-07-08 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('holder_name', models.CharField(max_length=100)),
                ('acc_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('Current', 'Current'), ('Saving', 'Saving')], max_length=100)),
                ('current_balance', models.PositiveBigIntegerField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banks.branch')),
            ],
        ),
    ]
