# Generated by Django 4.2.13 on 2024-07-11 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_acc_number_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='category',
            field=models.CharField(choices=[('CURRENT', 'Current'), ('SAVING', 'Saving')], max_length=100),
        ),
    ]
