# Generated by Django 4.2.13 on 2024-07-31 06:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(max_length=100)),
                ('expiry_time', models.DateTimeField(default=datetime.datetime(2024, 7, 31, 7, 7, 8, 528580, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
