# Generated by Django 4.2.13 on 2024-07-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('acc_holder_name', models.CharField(max_length=100)),
                ('acc_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('acc_type', models.CharField(choices=[('Current', 'Current'), ('Saving', 'Saving')], max_length=100)),
                ('current_balance', models.PositiveBigIntegerField()),
            ],
        ),
    ]
