# Generated by Django 4.2.13 on 2024-07-06 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank_accounts', '0001_initial'),
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='acc_holder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banks.bankbranch'),
        ),
    ]
